# Etapa 1: build da aplicação
FROM node:24-alpine AS builder

WORKDIR /app

# Copia os arquivos principais
COPY package.json package-lock.json* ./

# Instala dependências (sem dev)
RUN npm install --frozen-lockfile

# Copia o restante do código
COPY . .
COPY .env .env

# Gera Prisma Client
RUN npx prisma generate

# Compila o Next.js (App Router)
RUN npm run build

# Etapa 2: imagem final, mais enxuta
FROM node:24-alpine

WORKDIR /app

# Copia apenas o necessário da imagem builder
COPY --from=builder /app/package.json /app/package-lock.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.ts ./
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/src ./src
COPY --from=builder /app/.env .env

# Instala apenas dependências de produção
RUN npm install --omit=dev --frozen-lockfile

# Porta padrão do Next.js
EXPOSE 3000

# Comando de produção
CMD ["npm", "start"]