apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
type: Opaque
data:
  {{- range $key, $value := .Values.postgres.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}